//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio.Web.WSCURSO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/DB.Entities")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCurso {
            get {
                return this.IdCursoField;
            }
            set {
                if ((this.IdCursoField.Equals(value) != true)) {
                    this.IdCursoField = value;
                    this.RaisePropertyChanged("IdCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCurso {
            get {
                return this.NomeCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCursoField, value) != true)) {
                    this.NomeCursoField = value;
                    this.RaisePropertyChanged("NomeCurso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCURSO.ICursoSvc")]
    public interface ICursoSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/GetAllCursos", ReplyAction="http://tempuri.org/ICursoSvc/GetAllCursosResponse")]
        Exercicio.Web.WSCURSO.Curso[] GetAllCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/GetAllCursos", ReplyAction="http://tempuri.org/ICursoSvc/GetAllCursosResponse")]
        System.Threading.Tasks.Task<Exercicio.Web.WSCURSO.Curso[]> GetAllCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/GetCurso", ReplyAction="http://tempuri.org/ICursoSvc/GetCursoResponse")]
        Exercicio.Web.WSCURSO.Curso GetCurso(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/GetCurso", ReplyAction="http://tempuri.org/ICursoSvc/GetCursoResponse")]
        System.Threading.Tasks.Task<Exercicio.Web.WSCURSO.Curso> GetCursoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/InsertCurso", ReplyAction="http://tempuri.org/ICursoSvc/InsertCursoResponse")]
        void InsertCurso(Exercicio.Web.WSCURSO.Curso c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/InsertCurso", ReplyAction="http://tempuri.org/ICursoSvc/InsertCursoResponse")]
        System.Threading.Tasks.Task InsertCursoAsync(Exercicio.Web.WSCURSO.Curso c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/ModifyCurso", ReplyAction="http://tempuri.org/ICursoSvc/ModifyCursoResponse")]
        void ModifyCurso(Exercicio.Web.WSCURSO.Curso c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/ModifyCurso", ReplyAction="http://tempuri.org/ICursoSvc/ModifyCursoResponse")]
        System.Threading.Tasks.Task ModifyCursoAsync(Exercicio.Web.WSCURSO.Curso c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/RemoveCurso", ReplyAction="http://tempuri.org/ICursoSvc/RemoveCursoResponse")]
        void RemoveCurso(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoSvc/RemoveCurso", ReplyAction="http://tempuri.org/ICursoSvc/RemoveCursoResponse")]
        System.Threading.Tasks.Task RemoveCursoAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoSvcChannel : Exercicio.Web.WSCURSO.ICursoSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoSvcClient : System.ServiceModel.ClientBase<Exercicio.Web.WSCURSO.ICursoSvc>, Exercicio.Web.WSCURSO.ICursoSvc {
        
        public CursoSvcClient() {
        }
        
        public CursoSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Exercicio.Web.WSCURSO.Curso[] GetAllCursos() {
            return base.Channel.GetAllCursos();
        }
        
        public System.Threading.Tasks.Task<Exercicio.Web.WSCURSO.Curso[]> GetAllCursosAsync() {
            return base.Channel.GetAllCursosAsync();
        }
        
        public Exercicio.Web.WSCURSO.Curso GetCurso(int Id) {
            return base.Channel.GetCurso(Id);
        }
        
        public System.Threading.Tasks.Task<Exercicio.Web.WSCURSO.Curso> GetCursoAsync(int Id) {
            return base.Channel.GetCursoAsync(Id);
        }
        
        public void InsertCurso(Exercicio.Web.WSCURSO.Curso c) {
            base.Channel.InsertCurso(c);
        }
        
        public System.Threading.Tasks.Task InsertCursoAsync(Exercicio.Web.WSCURSO.Curso c) {
            return base.Channel.InsertCursoAsync(c);
        }
        
        public void ModifyCurso(Exercicio.Web.WSCURSO.Curso c) {
            base.Channel.ModifyCurso(c);
        }
        
        public System.Threading.Tasks.Task ModifyCursoAsync(Exercicio.Web.WSCURSO.Curso c) {
            return base.Channel.ModifyCursoAsync(c);
        }
        
        public void RemoveCurso(int Id) {
            base.Channel.RemoveCurso(Id);
        }
        
        public System.Threading.Tasks.Task RemoveCursoAsync(int Id) {
            return base.Channel.RemoveCursoAsync(Id);
        }
    }
}
