//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Curso
    {
        public int cod_curso { get; set; }
        public string nome_curso { get; set; }
    }
}
