//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio.Web.WSPRODUTO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/DB.Entities")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto {
            get {
                return this.NomeProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoField, value) != true)) {
                    this.NomeProdutoField = value;
                    this.RaisePropertyChanged("NomeProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdProduto {
            get {
                return this.QtdProdutoField;
            }
            set {
                if ((this.QtdProdutoField.Equals(value) != true)) {
                    this.QtdProdutoField = value;
                    this.RaisePropertyChanged("QtdProduto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPRODUTO.IProdutoSvc")]
    public interface IProdutoSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/GetAllProdutos", ReplyAction="http://tempuri.org/IProdutoSvc/GetAllProdutosResponse")]
        Exercicio.Web.WSPRODUTO.Produto[] GetAllProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/GetAllProdutos", ReplyAction="http://tempuri.org/IProdutoSvc/GetAllProdutosResponse")]
        System.Threading.Tasks.Task<Exercicio.Web.WSPRODUTO.Produto[]> GetAllProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/GetProduto", ReplyAction="http://tempuri.org/IProdutoSvc/GetProdutoResponse")]
        Exercicio.Web.WSPRODUTO.Produto GetProduto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/GetProduto", ReplyAction="http://tempuri.org/IProdutoSvc/GetProdutoResponse")]
        System.Threading.Tasks.Task<Exercicio.Web.WSPRODUTO.Produto> GetProdutoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/InsertProduto", ReplyAction="http://tempuri.org/IProdutoSvc/InsertProdutoResponse")]
        void InsertProduto(Exercicio.Web.WSPRODUTO.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/InsertProduto", ReplyAction="http://tempuri.org/IProdutoSvc/InsertProdutoResponse")]
        System.Threading.Tasks.Task InsertProdutoAsync(Exercicio.Web.WSPRODUTO.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/ModifyProduto", ReplyAction="http://tempuri.org/IProdutoSvc/ModifyProdutoResponse")]
        void ModifyProduto(Exercicio.Web.WSPRODUTO.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/ModifyProduto", ReplyAction="http://tempuri.org/IProdutoSvc/ModifyProdutoResponse")]
        System.Threading.Tasks.Task ModifyProdutoAsync(Exercicio.Web.WSPRODUTO.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/RemoveProduto", ReplyAction="http://tempuri.org/IProdutoSvc/RemoveProdutoResponse")]
        void RemoveProduto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoSvc/RemoveProduto", ReplyAction="http://tempuri.org/IProdutoSvc/RemoveProdutoResponse")]
        System.Threading.Tasks.Task RemoveProdutoAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoSvcChannel : Exercicio.Web.WSPRODUTO.IProdutoSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoSvcClient : System.ServiceModel.ClientBase<Exercicio.Web.WSPRODUTO.IProdutoSvc>, Exercicio.Web.WSPRODUTO.IProdutoSvc {
        
        public ProdutoSvcClient() {
        }
        
        public ProdutoSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Exercicio.Web.WSPRODUTO.Produto[] GetAllProdutos() {
            return base.Channel.GetAllProdutos();
        }
        
        public System.Threading.Tasks.Task<Exercicio.Web.WSPRODUTO.Produto[]> GetAllProdutosAsync() {
            return base.Channel.GetAllProdutosAsync();
        }
        
        public Exercicio.Web.WSPRODUTO.Produto GetProduto(int Id) {
            return base.Channel.GetProduto(Id);
        }
        
        public System.Threading.Tasks.Task<Exercicio.Web.WSPRODUTO.Produto> GetProdutoAsync(int Id) {
            return base.Channel.GetProdutoAsync(Id);
        }
        
        public void InsertProduto(Exercicio.Web.WSPRODUTO.Produto p) {
            base.Channel.InsertProduto(p);
        }
        
        public System.Threading.Tasks.Task InsertProdutoAsync(Exercicio.Web.WSPRODUTO.Produto p) {
            return base.Channel.InsertProdutoAsync(p);
        }
        
        public void ModifyProduto(Exercicio.Web.WSPRODUTO.Produto p) {
            base.Channel.ModifyProduto(p);
        }
        
        public System.Threading.Tasks.Task ModifyProdutoAsync(Exercicio.Web.WSPRODUTO.Produto p) {
            return base.Channel.ModifyProdutoAsync(p);
        }
        
        public void RemoveProduto(int Id) {
            base.Channel.RemoveProduto(Id);
        }
        
        public System.Threading.Tasks.Task RemoveProdutoAsync(int Id) {
            return base.Channel.RemoveProdutoAsync(Id);
        }
    }
}
